# Simplified nixpacks configuration for Railway
[phases.install]
cmds = ["cd fanfiq-app && npm ci"]

[phases.build]
cmds = ["cd fanfiq-app && npm run build"]

[start]
cmd = "cd fanfiq-app && npm start"